# Site settings
title: Đọc hiểu Pāḷi (Pāḷi learning)
description: Tài liệu ngữ pháp và từ vựng Pāḷi với giải thích tiếng Việt
baseurl: ""
url: "https://ducthotran2010.github.io"

# Build settings
markdown: kramdown
highlighter: rouge
theme: minima

# Kramdown settings for LaTeX support
kramdown:
  math_engine: mathjax
  input: GFM
  hard_wrap: false

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap

# Navigation
header_pages:
  - _languages/pali/index.md

# Collections for better organization
collections:
  languages:
    output: true
    permalink: /:path/

# Include custom CSS
sass:
  sass_dir: _sass
  style: compressed

# Defaults
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
      type: "languages"
    values:
      layout: "language"

# Exclude files from processing
exclude:
  - CLAUDE.md
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - .bundle
  - .sass-cache
  - _site